[AIRFLOW-3876] AttributeError: module 'distutils' has no attribute 'util'
fix for AttributeError: module 'distutils' has no attribute 'util'

(cherry picked from commit 1ae7f6f789667e40736392f554ae76e0f8916575)